from typing import Protocol, runtime_checkable
from .models import PhenomenonRecord


@runtime_checkable
class PhenomenonRepository(Protocol):
    def get(self, id: str) -> PhenomenonRecord: ...
    def get_children(self, parent_id: str) -> list[PhenomenonRecord]: ...
    def save(self, record: PhenomenonRecord) -> PhenomenonRecord: ...
    def list_all(self) -> list[PhenomenonRecord]: ...
    def delete(self, id: str) -> None: ...
